steps:
  # https://docs.aws.amazon.com/AmazonECS/latest/userguide/task-metadata-endpoint-v4-fargate.html
  - label: 'echo Task metadata endpoint version 4'
    command: echo ${ECS_CONTAINER_METADATA_URI_V4} # This path returns metadata for the container.

  - label: 'Example Test (just echo Hello)'
    command: echo "Hello!"

  # - label: 'Run NodeJS test build (just run `npm ci`)'
  #   key: nodejs-test-build
  #   commands:
  #     - npm ci
  #   plugins:
  #     - docker#v3.9.0:
  #         image: node:16

  # - label: ':ecs: :rocket:'
  #   concurrency_group: 'my-service-deploy'
  #   concurrency: 1
  #   plugins:
  #     - ecs-deploy#v1.4.1:
  #         cluster: 'defaultEcsCluster'
  #         service: 'my-service'
  #         task-definition: 'examples/hello-world.json'
  #         task-family: 'hello-world'
  #         image: '${ECR_REPOSITORY}/hello-world:${BUILDKITE_BUILD_NUMBER}'

  # - label: 'Run NodeJS test build'
  #   key: nodejs-test-build
  #   commands:
  #     - npm ci
  #   plugins:
  #     - docker#v3.9.0:
  #         image: node:16
