steps:
  - label: 'run docker command'
    command: docker

  # https://docs.aws.amazon.com/AmazonECS/latest/userguide/task-metadata-endpoint-v4-fargate.html
  - label: 'curl Task metadata endpoint version 4'
    # command: echo ${ECS_CONTAINER_METADATA_URI_V4} # This path returns metadata for the container.
    command: curl ${ECS_CONTAINER_METADATA_URI_V4} # This path returns metadata for the container.
    # {"DockerId":"d303d78e45fe46bab9da1d3fa8a57097-2034587672","Name":"bk-container","DockerName":"bk-container","Image":"buildkite/agent","ImageID":"sha256:68cec4dea2d2300882f33968968e501d1da66abcee2815aeafeee5a8567bfd22","Labels":{"com.amazonaws.ecs.cluster":"arn:aws:ecs:us-east-1:665077919718:cluster/ecsDefaultCluster","com.amazonaws.ecs.container-name":"bk-container","com.amazonaws.ecs.task-arn":"arn:aws:ecs:us-east-1:665077919718:task/ecsDefaultCluster/d303d78e45fe46bab9da1d3fa8a57097","com.amazonaws.ecs.task-definition-family":"test-bk-dd","com.amazonaws.ecs.task-definition-version":"4"},"DesiredStatus":"RUNNING","KnownStatus":"RUNNING","Limits":{"CPU":2},"CreatedAt":"2022-02-21T11:18:29.308091299Z","StartedAt":"2022-02-21T11:18:29.308091299Z","Type":"NORMAL","Networks":[{"NetworkMode":"awsvpc","IPv4Addresses":["10.0.0.179"],"AttachmentIndex":0,"MACAddress":"02:7d:b2:93:21:43","IPv4SubnetCIDRBlock":"10.0.0.0/24","DomainNameServers":["10.0.0.2"],"DomainNameSearchList":["ec2.internal"],"PrivateDNSName":"ip-10-0-0-179.ec2.internal","SubnetGatewayIpv4Address":"10.0.0.1/24"}],"ContainerARN":"arn:aws:ecs:us-east-1:665077919718:container/ecsDefaultCluster/d303d78e45fe46bab9da1d3fa8a57097/970f9b8b-987b-4e70-81fd-3a2023b2ee17","LogOptions":{"awslogs-group":"/ecs/test-bk-dd","awslogs-region":"us-east-1","awslogs-stream":"ecs/bk-container/d303d78e45fe46bab9da1d3fa8a57097"},"LogDriver":"awslogs"}

  - label: 'Example Test (just echo Hello)'
    command: echo "Hello!"

  # - label: 'Run NodeJS test build (just run `npm ci`)'
  #   key: nodejs-test-build
  #   commands:
  #     - npm ci
  #   plugins:
  #     - docker#v3.9.0:
  #         image: node:16

  # - label: ':ecs: :rocket:'
  #   concurrency_group: 'my-service-deploy'
  #   concurrency: 1
  #   plugins:
  #     - ecs-deploy#v1.4.1:
  #         cluster: 'defaultEcsCluster'
  #         service: 'my-service'
  #         task-definition: 'examples/hello-world.json'
  #         task-family: 'hello-world'
  #         image: '${ECR_REPOSITORY}/hello-world:${BUILDKITE_BUILD_NUMBER}'

  # - label: 'Run NodeJS test build'
  #   key: nodejs-test-build
  #   commands:
  #     - npm ci
  #   plugins:
  #     - docker#v3.9.0:
  #         image: node:16
